[package]
name = "tlsupgrade"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.23.12"
rustls-pemfile = "2.1.3"
tokio = {version="1.39.2",features=["full","fs","io-util"]}
tokio-rustls = "0.26.0"
